install.packages("quanteda")
install.packages("readtext")
install.packages("stringi")
install.packages("textstem")
install.packages("rvest")
install.packages("rtweet")
install.packages("tesseract")
install.packages("pdftools")
install.packages("topicmodels")
install.packages("LDAvis")
install.packages("stm")
install.packages("spacyr")

library(spacyr)
spacy_install()
spacy_initialize()
